name: ddal
channels:
  - default
  - conda-forge
dependencies:
  - python=3.9
  - conda-forge::jupyterhub=3.0.0
  - pytorch::pytorch=1.13.0
  - pytorch::torchvision=0.13.1
  - pytorch::torchaudio=0.12.1
  - conda-forge::geopandas=0.12.1
  - conda-forge::rioxarray=0.13.1
  - conda-forge::scikit-learn=1.1.3
  - conda-forge::matplotlib
  - pip
  - pip:
    - pyodm
    - rastervision==0.13