name: ddal
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - mamba
  - notebook
  - jupyterhub
  - jupyterlab
  - altair
  - beautifulsoup4
  - bokeh
  - bottleneck
  - cloudpickle
  - conda-forge::blas[build=openblas]
  - cython
  - dask
  - dill
  - h5py
  - ipympl
  - ipywidgets
  - matplotlib-base
  - numba
  - numexpr
  - pandas
  - patsy
  - protobuf
  - pytables
  - scikit-image
  - scikit-learn
  - scipy
  - seaborn
  - sqlalchemy
  - statsmodels
  - sympy
  - widgetsnbextension
  - xlrd
  - ca-certificates
  - certifi
  - openssl
  - rioxarray==0.13.1
  - geopandas==0.12.1
  - pytorch::torchaudio
  - pytorch::cpuonly
  - pytorch::torchvision
  - pytorch::pytorch
  - accelerate
  - diffusers
